spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flowable_springboot?serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: root
    password: root
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
flowable:
  async-executor-activate: false #关闭定时任务job
  #將databaseSchemaUpdate没置为true。当Flowable发现库与数据库表结构不一致时，会自动将数据库表给开级至新版本。
  #所以，一般情况下，只有第一次是true，之后都要改成false，否则可能在没有备份表的情况下把数据表结构升级
  database-schema-update: true
server:
  port: 8082

